ENABLE:
  - BASH
  - DOCKERFILE
  - EDITORCONFIG
  - JSON
  - MARKDOWN
  - YAML

DISABLE_LINTERS:
  - YAML_V8R

GITHUB_STATUS_REPORTER: true

JSON_JSONLINT_ARGUMENTS: ["--comments"]

JSON_PRETTIER_ARGUMENTS: ["--trailing-comma", "none"]

SARIF_REPORTER: true
